### PR TITLE
Skyblock Updates. Entire API is Up to Date!!

### PR DESCRIPTION
**Pull request by Unexpextxd**
I'm so happy I could update this for yall. Have a nice day. I'll be using this ;)

### CODE REVIEW

**Comment by Unexpextxd** [comment]
Creating my own fork of this. Closing.

**Comment by Unexpextxd** [comment]
Creating my own fork.

**Comment by mat-1** [comment]
Thank you for this! Can you please re-open it? If you'd like I can add you as a maintainer on this repo since I don't have much time to actively maintain it myself.

**Comment by Unexpextxd** [comment]
Yep.

**Pull request merged**
